export const campaigns = [
    {
      id: 1,
      title: 'Campaign One',
      story: 'This is a story about Campaign One.',
      fundsRaised: '1.0 SOL',
      target: '3.0 SOL',
      creatorAddress: '5Mp1uPbhgV8ux1FvJqsLrSfpANkXLwH4xceEjBfWKuuS',
    },
    {
      id: 2,
      title: 'Campaign Two',
      story: 'This is a story about Campaign Two.',
      fundsRaised: '0.5 SOL',
      target: '2.0 SOL',
      creatorAddress: '5Mp1uPbhgV8ux1FvJqsLrSfpANkXLwH4xceEjBfWKuuS',
    },
    {
      id: 3,
      title: 'Campaign Three',
      story: 'This is a story about Campaign Three.',
      fundsRaised: '1.5 SOL',
      target: '4.0 SOL',
      creatorAddress: '5Mp1uPbhgV8ux1FvJqsLrSfpANkXLwH4xceEjBfWKuuS',
    },
    {
      id: 4,
      title: 'Campaign Four',
      story: 'This is a story about Campaign Four.',
      fundsRaised: '2.0 SOL',
      target: '5.0 SOL',
      creatorAddress: '5Mp1uPbhgV8ux1FvJqsLrSfpANkXLwH4xceEjBfWKuuS',
    },
    {
      id: 5,
      title: 'Campaign Five',
      story: 'This is a story about Campaign Five.',
      fundsRaised: '0.8 SOL',
      target: '3.5 SOL',
      creatorAddress: '5Mp1uPbhgV8ux1FvJqsLrSfpANkXLwH4xceEjBfWKuuS',
    },
    // Additional dummy campaigns
    {
      id: 6,
      title: 'Campaign Six',
      story: 'This is a story about Campaign Six.',
      fundsRaised: '0.9 SOL',
      target: '3.2 SOL',
      creatorAddress: '5Mp1uPbhgV8ux1FvJqsLrSfpANkXLwH4xceEjBfWKuuS',
    },
    {
        id: 7,
        title: 'Campaign Two',
        story: 'This is a story about Campaign Two.',
        fundsRaised: '0.5 SOL',
        target: '2.0 SOL',
        creatorAddress: '5Mp1uPbhgV8ux1FvJqsLrSfpANkXLwH4xceEjBfWKuuS',
      },
      {
        id: 8,
        title: 'Campaign Three',
        story: 'This is a story about Campaign Three.',
        fundsRaised: '1.5 SOL',
        target: '4.0 SOL',
        creatorAddress: '5Mp1uPbhgV8ux1FvJqsLrSfpANkXLwH4xceEjBfWKuuS',
      },
      {
        id: 9,
        title: 'Campaign Four',
        story: 'This is a story about Campaign Four.',
        fundsRaised: '2.0 SOL',
        target: '5.0 SOL',
        creatorAddress: '5Mp1uPbhgV8ux1FvJqsLrSfpANkXLwH4xceEjBfWKuuS',
      },
      {
        id: 10,
        title: 'Campaign Five',
        story: 'This is a story about Campaign Five.',
        fundsRaised: '0.8 SOL',
        target: '3.5 SOL',
        creatorAddress: '5Mp1uPbhgV8ux1FvJqsLrSfpANkXLwH4xceEjBfWKuuS',
      },
  ];